### PR TITLE
Start RunLoop.main, run Vapor app on background thread

### PR DESCRIPTION
**Pull request by vzsg**
It was reported in https://github.com/vapor/vapor/issues/2648 (but has actually plagued all Vapor versions of the past), the current template does not play nice with certain Foundation/AppKit classes and some third-party libraries that try to interact with the main queue.

Following the suggestions of the issue, this PR starts the Vapor Application on a background thread and parks the main thread in Dispatch, and calls `exit(3)` to terminate the process after the Vapor app returned. This new addendum allows the app to shut down properly in response to ^C and other signals.

### CODE REVIEW

**Comment by 0xTim** [comment]
@Lukasa can you think of any negative side effects this would have?

**Comment by Lukasa** [comment]
I'd replace the call to `RunLoop.run()` with `dispatchMain()`. I don't think anything else should matter.

**Comment by vzsg** [comment]
What difference does calling dispatchMain directly make? I've seen mentions of how you have to pick one (like [here](https://developer.apple.com/documentation/dispatch/dispatchqueue/1781006-main) and [here](https://developer.apple.com/documentation/dispatch/1452860-dispatchmain), sometimes with "does not have to" instead of the stronger MUST NOT), but not much about the weight of the options.

**Comment by djbe** [comment]
I've been relying on something like this to have an async configure/run, and a runloop as mentioned above. Honestly not sure if it's better or worse 🤷 

```swift
extension Application {
	private static let runQueue = DispatchQueue(label: "Run")

	/// We need to avoid blocking the main thread, so spin this off to a separate queue
	func run() async throws {
		try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
			Self.runQueue.async { [self] in
				do {
					try run()
					continuation.resume()
				} catch {
					continuation.resume(throwing: error)
				}
			}
		}
	}
}

@main
enum Run {
	static func main() async throws {
		var env = try Environment.detect()
		try LoggingSystem.bootstrap(from: &env)
		let app = Application(env)
		defer { app.shutdown() }

		try await configure(app)
		try await app.run()
	}
}
```

**Comment by vzsg** [comment]
That's actually very interesting IMHO 👍🏻

**Comment by Lukasa** [comment]
It's definitely a good idea to use the async `@main` dance if you can: actually invoking the main queue is annoying.

> What difference does calling dispatchMain directly make?

All three are essentially identical except that the Dispatch library is technically lower-level than Foundation, and applications that don't want to use Foundation can still use Dispatch. As a result I have a preference to use the Dispatch spelling of something where it's practical to do so.

**Comment by 0xTim** [comment]
(Reminder for self - need to ensure backtrace still works correctly)

**Comment by 0xTim** [comment]
(Reminded for self - need to check backtrace still works correctly)

**Review by cristiancardosodexcom — APPROVED** [review]
LGTM 👍

**Comment by vzsg** [comment]
TBF, the entry point in djbe's comment above is vastly superior to this PR.
I should probably just redo my commit based on that.

**Comment by vzsg** [comment]
(Live reaction to the last two CI failures) Gah, of course, if something is looking for main.swift, it doesn't matter if I have the Run target or not, there's not going to be a main.swift. That's about enough of this.

**Comment by 0xTim** [comment]
Closing this as this was resolved in #98

**Pull request closed without merging**
