### PR TITLE
Update last non-"async/await" routes to preferred "async/await" style

### LINKED ISSUE #89: Add a trivial `async` example route to "bare" template
In considering vapor/vapor#2858, I wonder if a trivial `async` example route should be added to the "bare" template?

Having both a non-`async` and `async` example would illustrate a fundamental concept of Vapor, and provide an easy reference when the usage intent is to spin up a new app with a single endpoint that needs to call an `async` function. Vapor newcomers may also tend to generate using a "bare" template at the start of their learning (I know I did).

Or, the existing "It works!" and "Hello, world!" examples could be changed to use the `async` form if that form is generally encouraged for new apps?

I put some thought into what a trivial additional `async` example could be:

## `Task.sleep` for a couple seconds

I like this option the most, followed by not doing any actual `async` work (the first alternative below). Having an `await` statement in the body of the function helps communicate the purpose of the example.

One drawback: a real app should never call `Task.sleep`, so this could inadvertently suggest a bad practice.

``` swift
// Sources/App/routes.swift
import Vapor

func routes(_ app: Application) throws {
    app.get { req in
        return "It works!"
    }

    app.get("hello") { req -> String in
        return "Hello, world!"
    }

    app.get("async") { req async throws -> String in
        let nanosecondsPerSec: UInt64 = 1_000_000_000
        try await Task.sleep(nanoseconds: 2 * nanosecondsPerSec)
        return "Hello, async style!"
    }
}
```

> Note: The global constant `NSEC_PER_SEC` is generally used to calculate a quantity of nanoseconds, but that's defined in `libdispatch`, which isn't really usable yet on non-Apple platforms (not that easily, at least). The nice time and duration APIs in Swift 5.7 will remove the need to calculate nanoseconds at all.

## Alternative: Don't include any actual async work

``` swift
// Sources/App/routes.swift
import Vapor

func routes(_ app: Application) throws {
    app.get { req in
        return "It works!"
    }

    app.get("hello") { req -> String in
        return "Hello, world!"
    }

    app.get("async") { req async throws -> String in
        return "Hello, async style!"
    }
}
```

This is still significantly differentiated from the non-async style "hello" function: it differs by the path segment, `async throws` in the signature, and the return value. That differentiation doesn't illustrate purpose, tho.

## Alternative: Make a URL request (bad idea)

``` swift
// Sources/App/routes.swift
import Vapor

func routes(_ app: Application) throws {
    app.get { req in
        return "It works!"
    }

    app.get("hello") { req -> String in
        return "Hello, world!"
    }

    app.get("async") { req async throws -> String in
        let urlRequest = URLRequest(url: URL(string: "http://example.com")!)
        let (data, response) = try await URLSession.shared.data(for: urlRequest)
        if let httpResponse = response as? HTTPURLResponse,
           httpResponse.statusCode != 200 {
            return "Error while fetching data"
        }
        return String(decoding: data, as: UTF8.self)
    }
}
```

A URL request is a familiar illustration, but this would depend on `FoundationNetworking` on non-Apple platforms, additionally needing:

``` swift
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
```

And, the default Dockerfile omits `FoundationNetworking`'s `libcurl4 ` dependency to produce a smaller binary by default. The default Dockerfile should definitely successfully build the freshly generated app, and adding a heavy dependency to merely gain a usage example is a non-starter.

Making a real request to a hosted service in an app template can be inconsiderate to the host unless it's specifically meant for that kind of use. (I know example.com is meant for use in sample code, but I don't know whether it's meant for code that will actually be run.)

In some scenarios, good security policy may also block outgoing network traffic by default.

Lastly, the above URL request code doesn't compile on Swift 5.6 (I only tested linux). I didn't bother investigating why, but it seems the `async` variation of `URLSession.shared.data(for:)` was introduced in Swift 5.7, or perhaps the compiler's type inference just needs some helpful annotations. The example already isn't promising and isn't that trivial, and may be even more noisy once made to work on Swift 5.6.

### PR DESCRIPTION
**Pull request by gohanlon**
Resolves #89.

### CODE REVIEW

**Comment by gohanlon** [comment]
Tested "bare":

``` text
% vapor new test-all-routes-async-bare \
  --no-leaf --no-fluent \
  --template https://github.com/gohanlon/vapor-template --branch all-routes-async
% cd test-all-routes-async-bare && swift build && swift run

% curl localhost:8080
It works!
% curl localhost:8080/hello
Hello, world!

% docker compose build && docker compose up
% curl localhost:8080
It works!
% curl localhost:8080/hello
Hello, world!
```

Tested with `--leaf`:

``` text
% vapor new test-all-routes-async-leaf \
  --leaf --no-fluent \
  --template https://github.com/gohanlon/vapor-template --branch all-routes-async
% cd test-all-routes-async-leaf && swift build && swift run

% curl localhost:8080      
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Hello Vapor!</title>
</head>

<body>
  <h1>Hello Vapor!</h1>
</body>
</html>                                                                                                                                                                                                                                                                                                  
% curl localhost:8080/hello
Hello, world!

% docker compose build && docker compose up
% curl localhost:8080      
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Hello Vapor!</title>
</head>

<body>
  <h1>Hello Vapor!</h1>
</body>
</html>                                                                                                                                                                                                                                                                                                  
% curl localhost:8080/hello
Hello, world!
```

**Comment by gohanlon** [comment]
A couple specific notes:

* I kept the inferred return type on the default route, and kept explicit return type on “hello”. Let me know if that's still preferred.
* Would you prefer omitting the explicit `return`s? (These are all single-expression closures.)

**Review by 0xTim — APPROVED** [review]
Thanks! Yeah you can remove the `return` if you'd like

**Comment by gohanlon** [comment]
I removed the explicit `return`s, and I repeated the same [test procedure](https://github.com/vapor/template/pull/91#issuecomment-1189705640). Let me know if there's anything else, otherwise this is ready to go!

**Pull request merged**
