### PR TITLE
Update CI to run on push and pull

### LINKED ISSUE #67: Add CI to test the template
~~Currently any PRs don't have CI, we should fix this~~

We should add some CI to test PRs that does the following:

* Build the toolbox
* Run `vapor new` for the various permutations
* Build the Docker container

We can base some of it on https://github.com/vapor/toolbox/blob/main/.github/workflows/test.yml#L8-L31

### PR DESCRIPTION
**Pull request by RishiKumarRay**
fixed #67 

Update CI to run on push and pull

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
Thanks!

**Comment by RishiKumarRay** [comment]
@0xTim there is some user password error that is making this fail

**Comment by 0xTim** [comment]
@RishiKumarRay OK yeah this is completely my fault. The issue is wrong.

The current workflow generates the downstream templates, that should stay on just `main` (essentially it keeps the downstream templates up to date)

We need to add a new CI. That should build the toolbox and then run a number of checks. Essentially we can copy most of https://github.com/vapor/toolbox/blob/main/.github/workflows/test.yml#L8-L31, but build the toolbox in release, check that all the different permutations of the template work and then build the docker containers to ensure that the actual code works. Make sense?

**Comment by 0xTim** [comment]
Closing this in favour of #69

**Pull request closed without merging**
