### PR TITLE
Help out the typechecker to reduce build times

### PR DESCRIPTION
**Pull request by gwynne**
Fixes vapor/fluent-mysql-driver#219.

### CODE REVIEW

**Comment by MahdiBM** [comment]
not building: 
```
error: fatalError
/Users/mahdibm/Github/template/Package.swift:15:120: error: '/' is not a prefix unary operator
        .package(url: "https://github.com/vapor/fluent-{{fluent.db.url}}-driver.git", from: "{{fluent.db.version}}"),{{/fluent}}{{#leaf}}
                                                                                                                       ^
/Users/mahdibm/Github/template/Package.swift:15:121: error: cannot find 'fluent' in scope
        .package(url: "https://github.com/vapor/fluent-{{fluent.db.url}}-driver.git", from: "{{fluent.db.version}}"),{{/fluent}}{{#leaf}}
                                                                                                                        ^~~~~~
/Users/mahdibm/Github/template/Package.swift:17:77: error: '/' is not a prefix unary operator
        .package(url: "https://github.com/vapor/leaf.git", from: "4.2.4"),{{/leaf}}
                                                                            ^
/Users/mahdibm/Github/template/Package.swift:17:78: error: cannot find 'leaf' in scope
        .package(url: "https://github.com/vapor/leaf.git", from: "4.2.4"),{{/leaf}}
                                                                             ^~~~
/Users/mahdibm/Github/template/Package.swift:24:114: error: '/' is not a prefix unary operator
                .product(name: "Fluent{{fluent.db.module}}Driver", package: "fluent-{{fluent.db.url}}-driver"),{{/fluent}}{{#leaf}}
                                                                                                                 ^
/Users/mahdibm/Github/template/Package.swift:24:115: error: cannot find 'fluent' in scope
                .product(name: "Fluent{{fluent.db.module}}Driver", package: "fluent-{{fluent.db.url}}-driver"),{{/fluent}}{{#leaf}}
                                                                                                                  ^~~~~~
/Users/mahdibm/Github/template/Package.swift:25:59: error: '/' is not a prefix unary operator
                .product(name: "Leaf", package: "leaf"),{{/leaf}}
                                                          ^
/Users/mahdibm/Github/template/Package.swift:25:60: error: cannot find 'leaf' in scope
                .product(name: "Leaf", package: "leaf"),{{/leaf}}
                                                           ^~~~
/Users/mahdibm/Github/template/Package.swift:15:132: error: no macro named 'leaf'
        .package(url: "https://github.com/vapor/fluent-{{fluent.db.url}}-driver.git", from: "{{fluent.db.version}}"),{{/fluent}}{{#leaf}}
                                                                                                                                   ^~~~
/Users/mahdibm/Github/template/Package.swift:4:15: error: type of expression is ambiguous without a type annotation
let package = Package(
              ^~~~~~~~

 *  The terminal process "swift 'package', 'resolve'" terminated with exit code: 1. 
```

**Comment by MahdiBM** [comment]
the `/`seems extra? I haven't looked into how the template stuff work.

**Comment by MahdiBM** [comment]
Interesting ... the `/` doesn't seem extra now, but still not sure why it isn't building in my local computer.

**Comment by MahdiBM** [comment]
Wait this isn't even supposed to build? 🧐

**Comment by gwynne** [comment]
@MahdiBM It doesn't build out of the box, no; the template has to be processed through `vapor new` to produce a repo.

**Comment by MahdiBM** [comment]
yeah i noticed, it's building after `vapor new test_fl --branch gwynne-patch-1`. Let's see if it builds fast enough ....

**Comment by MahdiBM** [comment]
45s here on M1 macbook. That's still much better than the 72s you reported on a M1, although not quite as low as 29s which is probably due to my local problems.

**Review by MahdiBM — APPROVED** [review]

**Comment by gwynne** [comment]
The 29s was with running `swift package resolve` separately and thus not taking the additional ~30s required for the git checkouts and dependency resolution.

**Pull request merged**
